menu:
  Home: /
  Archives: /archives
  About: /about

# duoshuo comment 已废弃
duoshuo: false
duoshuo_name:

# disqus comment
disqus: true
disqus_shortname: boseny-blog

# livere comment
livere: false
livere_uid: MTAyMC8zMzYwMC8xMDE1NQ==


# youyan comment
youyan: false
youyan_uid: 2156653
# google analytics
googleTrackId:

toc:
  enable: true


anchorjs: true